<?php

namespace Vendor\Waha\Facades;

use Illuminate\Support\Facades\Facade;

/**
 * AUTO-GENERATED IDE HELPER (DO NOT EDIT MANUALLY)
 *
 * @method static \Vendor\Waha\OpenApi\WahaApiProxy host(string $hostKey)
 * @method static \Vendor\Waha\OpenApi\WahaManagerProxy debug()
 * @method static \Vendor\Waha\OpenApi\WahaManagerProxy asArray()
 * @method static \Vendor\Waha\OpenApi\WahaManagerProxy asJson()
 * @method static \Vendor\Waha\OpenApi\WahaManagerProxy asModel()
 * @method static ?array lastHttp()
 * @method static ?string lastHttpCurl()
 * @method static mixed withDebug(callable $fn)
 *
 * @method static \Vendor\Waha\OpenApi\Tags\SessionsTag sessions()
 * @method static \Vendor\Waha\OpenApi\Tags\PairingTag pairing()
 * @method static \Vendor\Waha\OpenApi\Tags\ProfileTag profile()
 * @method static \Vendor\Waha\OpenApi\Tags\ChattingTag chatting()
 * @method static \Vendor\Waha\OpenApi\Tags\PresenceTag presence()
 * @method static \Vendor\Waha\OpenApi\Tags\ChannelsTag channels()
 * @method static \Vendor\Waha\OpenApi\Tags\StatusTag status()
 * @method static \Vendor\Waha\OpenApi\Tags\ChatsTag chats()
 * @method static \Vendor\Waha\OpenApi\Tags\ApiKeysTag apiKeys()
 * @method static \Vendor\Waha\OpenApi\Tags\ContactsTag contacts()
 * @method static \Vendor\Waha\OpenApi\Tags\GroupsTag groups()
 * @method static \Vendor\Waha\OpenApi\Tags\CallsTag calls()
 * @method static \Vendor\Waha\OpenApi\Tags\EventsTag events()
 * @method static \Vendor\Waha\OpenApi\Tags\LabelsTag labels()
 * @method static \Vendor\Waha\OpenApi\Tags\MediaTag media()
 * @method static \Vendor\Waha\OpenApi\Tags\AppsTag apps()
 * @method static \Vendor\Waha\OpenApi\Tags\ObservabilityTag observability()
 * @method static \Vendor\Waha\OpenApi\Tags\StorageTag storage()
 *
 * @method static mixed getQR(?string $format = 'image', ?string $session = null)
 * @method static mixed requestCode(string $phoneNumber, ?string $method = null, ?string $session = null)
 * @method static mixed screenshot(?string $session = null)
 * @method static \Vendor\Waha\Generated\Model\MeInfo getMe(?string $session = null)
 * @method static \Vendor\Waha\Generated\Model\SessionDTO restart(?string $session = null)
 * @method static \Vendor\Waha\Generated\Model\MyProfile getMyProfile(?string $session = null)
 * @method static \Vendor\Waha\Generated\Model\Result setProfileName(string $name, ?string $session = null)
 * @method static \Vendor\Waha\Generated\Model\Result setProfileStatus(string $status, ?string $session = null)
 * @method static \Vendor\Waha\Generated\Model\Result setProfilePicture(mixed $file, ?string $session = null)
 * @method static \Vendor\Waha\Generated\Model\Result deleteProfilePicture(?string $session = null)
 * @method static \Vendor\Waha\Generated\Model\WAMessage sendText(string $chatId, string $text, ?string $reply_to = null, ?bool $linkPreview = true, ?bool $linkPreviewHighQuality = false, ?string $session = null)
 * @method static array sendTextGet(?string $phone = null, ?string $text = null, ?string $session = null)
 * @method static array sendImage(string $chatId, mixed $file, ?string $reply_to = null, ?string $caption = null, ?string $session = null)
 * @method static array sendFile(string $chatId, mixed $file, ?string $reply_to = null, ?string $caption = null, ?string $session = null)
 * @method static array sendVoice(string $chatId, mixed $file, bool $convert, ?string $reply_to = null, ?string $session = null)
 * @method static mixed sendVideo(string $chatId, mixed $file, bool $convert, ?string $reply_to = null, ?bool $asNote = null, ?string $caption = 'Just watch at this!', ?string $session = null)
 * @method static array sendLinkCustomPreview(string $chatId, string $text, \Vendor\Waha\Generated\Model\LinkPreviewData $preview, ?string $reply_to = null, ?bool $linkPreviewHighQuality = true, ?string $session = null)
 * @method static mixed sendButtons(string $chatId, string $header, string $body, string $footer, array $buttons, mixed $headerImage = null, ?string $session = null)
 * @method static array sendList(string $chatId, mixed $message, ?string $reply_to = null, ?string $session = null)
 * @method static \Vendor\Waha\Generated\Model\WAMessage forwardMessage(string $chatId, string $messageId, ?string $session = null)
 * @method static array sendSeen(string $chatId, ?string $messageId = null, ?array $messageIds = null, ?string $participant = null, ?string $session = null)
 * @method static mixed startTyping(string $chatId, ?string $session = null)
 * @method static mixed stopTyping(string $chatId, ?string $session = null)
 * @method static array setReaction(string $messageId, string $reaction, ?string $session = null)
 * @method static mixed setStar(string $messageId, string $chatId, bool $star, ?string $session = null)
 * @method static mixed sendPoll(string $chatId, \Vendor\Waha\Generated\Model\MessagePoll $poll, ?string $reply_to = null, ?string $session = null)
 * @method static mixed sendPollVote(string $chatId, string $pollMessageId, array $votes, ?float $pollServerId = null, ?string $session = null)
 * @method static array sendLocation(string $chatId, float $latitude, float $longitude, string $title, ?string $reply_to = null, ?string $session = null)
 * @method static mixed sendContactVcard(string $chatId, array $contacts, ?string $reply_to = null, ?string $session = null)
 * @method static mixed sendButtonsReply(string $chatId, string $selectedDisplayText, string $selectedButtonID, ?string $replyTo = null, ?string $session = null)
 * @method static array getMessages(?string $sortBy = 'timestamp', ?string $sortOrder = null, ?bool $downloadMedia = true, ?string $chatId = null, ?float $limit = 10, ?float $offset = null, ?float $filter_timestamp_lte = null, ?float $filter_timestamp_gte = null, ?bool $filter_fromMe = null, ?string $filter_ack = null, ?string $session = null)
 * @method static \Vendor\Waha\Generated\Model\WANumberExistResult checkNumberStatus(?string $phone = null, ?string $session = null)
 * @method static array reply(string $chatId, string $text, ?string $reply_to = null, ?bool $linkPreview = true, ?bool $linkPreviewHighQuality = false, ?string $session = null)
 * @method static mixed dEPRECATED(string $chatId, string $url, string $title, ?string $session = null)
 * @method static mixed getChats(?string $sortBy = null, ?string $sortOrder = null, ?float $limit = null, ?float $offset = null, ?string $session = null)
 * @method static array getChatsOverview(?float $limit = 20, ?float $offset = null, ?array $ids = null, ?string $session = null)
 * @method static array postChatsOverview(\Vendor\Waha\Generated\Model\OverviewPaginationParams $pagination, \Vendor\Waha\Generated\Model\OverviewFilter $filter, ?string $session = null)
 * @method static mixed deleteChat(string $chatId, ?string $session = null)
 * @method static array getChatMessages(string $chatId, ?string $sortBy = 'timestamp', ?string $sortOrder = null, ?bool $downloadMedia = true, ?float $limit = 10, ?float $offset = null, ?float $filter_timestamp_lte = null, ?float $filter_timestamp_gte = null, ?bool $filter_fromMe = null, ?string $filter_ack = null, ?string $session = null)
 * @method static mixed clearMessages(string $chatId, ?string $session = null)
 * @method static \Vendor\Waha\Generated\Model\ReadChatMessagesResponse readChatMessages(string $chatId, ?float $messages = null, ?float $days = 7, ?string $session = null)
 * @method static \Vendor\Waha\Generated\Model\WAMessage getChatMessage(string $chatId, string $messageId, ?bool $downloadMedia = true, ?string $session = null)
 * @method static mixed deleteMessage(string $chatId, string $messageId, ?string $session = null)
 * @method static mixed editMessage(string $chatId, string $messageId, string $text, ?bool $linkPreview = true, ?bool $linkPreviewHighQuality = false, ?string $session = null)
 * @method static mixed pinMessage(string $chatId, string $messageId, float $duration, ?string $session = null)
 * @method static mixed unpinMessage(string $chatId, string $messageId, ?string $session = null)
 * @method static array archiveChat(string $chatId, ?string $session = null)
 * @method static array unarchiveChat(string $chatId, ?string $session = null)
 * @method static array unreadChat(string $chatId, ?string $session = null)
 * @method static mixed rejectCall(string $from, string $id, ?string $session = null)
 * @method static array previewChannelMessages(mixed $id, ?bool $downloadMedia = false, ?float $limit = 10, ?string $session = null)
 * @method static mixed follow(mixed $id, ?string $session = null)
 * @method static mixed unfollow(mixed $id, ?string $session = null)
 * @method static mixed mute(mixed $id, ?string $session = null)
 * @method static mixed unmute(mixed $id, ?string $session = null)
 * @method static \Vendor\Waha\Generated\Model\ChannelListResult searchByView(string $view, array $countries, array $categories, float $limit, string $startCursor, ?string $session = null)
 * @method static \Vendor\Waha\Generated\Model\ChannelListResult searchByText(string $text, array $categories, float $limit, string $startCursor, ?string $session = null)
 * @method static array getSearchViews(?string $session = null)
 * @method static array getSearchCountries(?string $session = null)
 * @method static array getSearchCategories(?string $session = null)
 * @method static mixed sendTextStatus(string $text, string $backgroundColor, float $font, ?string $id = null, ?array $contacts = null, ?bool $linkPreview = true, ?bool $linkPreviewHighQuality = false, ?string $session = null)
 * @method static mixed sendImageStatus(mixed $file, ?string $id = null, ?array $contacts = null, ?string $caption = null, ?string $session = null)
 * @method static mixed sendVoiceStatus(mixed $file, bool $convert, string $backgroundColor, ?string $id = null, ?array $contacts = null, ?string $session = null)
 * @method static mixed sendVideoStatus(mixed $file, bool $convert, ?string $id = null, ?array $contacts = null, ?string $caption = null, ?string $session = null)
 * @method static mixed deleteStatus(?string $id = null, ?array $contacts = null, ?string $session = null)
 * @method static \Vendor\Waha\Generated\Model\NewMessageIDResponse getNewMessageId(?string $session = null)
 * @method static array getChatLabels(string $chatId, ?string $session = null)
 * @method static mixed putChatLabels(string $chatId, array $labels, ?string $session = null)
 * @method static mixed getChatsByLabel(string $labelId, ?string $session = null)
 * @method static \Vendor\Waha\Generated\Model\WANumberExistResult checkExists(?string $phone = null, ?string $session = null)
 * @method static mixed getAbout(?string $contactId = null, ?string $session = null)
 * @method static mixed getProfilePicture(?string $contactId = null, ?bool $refresh = false, ?string $session = null)
 * @method static mixed block(string $contactId, ?string $session = null)
 * @method static mixed unblock(string $contactId, ?string $session = null)
 * @method static \Vendor\Waha\Generated\Model\Result put(string $chatId, string $firstName, string $lastName, ?string $session = null)
 * @method static \Vendor\Waha\Generated\Model\CountResponse getLidsCount(?string $session = null)
 * @method static \Vendor\Waha\Generated\Model\LidToPhoneNumber findPNByLid(string $lid, ?string $session = null)
 * @method static \Vendor\Waha\Generated\Model\LidToPhoneNumber findLIDByPhoneNumber(string $phoneNumber, ?string $session = null)
 * @method static mixed createGroup(string $name, array $participants, ?string $session = null)
 * @method static array getGroups(?string $sortBy = null, ?string $sortOrder = null, ?float $limit = null, ?float $offset = null, ?array $exclude = null, ?string $session = null)
 * @method static array joinInfoGroup(?string $code = null, ?string $session = null)
 * @method static \Vendor\Waha\Generated\Model\JoinGroupResponse joinGroup(string $code, ?string $session = null)
 * @method static \Vendor\Waha\Generated\Model\CountResponse getGroupsCount(?string $session = null)
 * @method static mixed refreshGroups(?string $session = null)
 * @method static mixed getGroup(string $id, ?string $session = null)
 * @method static mixed deleteGroup(string $id, ?string $session = null)
 * @method static mixed leaveGroup(string $id, ?string $session = null)
 * @method static \Vendor\Waha\Generated\Model\Result setPicture(string $id, mixed $file, ?string $session = null)
 * @method static \Vendor\Waha\Generated\Model\Result deletePicture(string $id, ?string $session = null)
 * @method static mixed setDescription(string $id, string $description, ?string $session = null)
 * @method static mixed setSubject(string $id, string $subject, ?string $session = null)
 * @method static mixed setInfoAdminOnly(string $id, bool $adminsOnly, ?string $session = null)
 * @method static \Vendor\Waha\Generated\Model\SettingsSecurityChangeInfo getInfoAdminOnly(string $id, ?string $session = null)
 * @method static mixed setMessagesAdminOnly(string $id, bool $adminsOnly, ?string $session = null)
 * @method static \Vendor\Waha\Generated\Model\SettingsSecurityChangeInfo getMessagesAdminOnly(string $id, ?string $session = null)
 * @method static string getInviteCode(string $id, ?string $session = null)
 * @method static string revokeInviteCode(string $id, ?string $session = null)
 * @method static mixed getParticipants(string $id, ?string $session = null)
 * @method static array getGroupParticipants(string $id, ?string $session = null)
 * @method static mixed addParticipants(string $id, array $participants, ?string $session = null)
 * @method static mixed removeParticipants(string $id, array $participants, ?string $session = null)
 * @method static mixed promoteToAdmin(string $id, array $participants, ?string $session = null)
 * @method static mixed demoteToAdmin(string $id, array $participants, ?string $session = null)
 * @method static mixed setPresence(string $chatId, string $presence, ?string $session = null)
 * @method static array getPresenceAll(?string $session = null)
 * @method static \Vendor\Waha\Generated\Model\WAHAChatPresences getPresence(string $chatId, ?string $session = null)
 * @method static mixed subscribe(string $chatId, ?string $session = null)
 * @method static \Vendor\Waha\Generated\Model\WAMessage sendEvent(string $chatId, \Vendor\Waha\Generated\Model\EventMessage $event, ?string $reply_to = null, ?string $session = null)
 * @method static \Vendor\Waha\Generated\Model\PingResponse ping()
 * @method static array check()
 * @method static array environment(?bool $all = false)
 * @method static mixed cpuProfile(?float $seconds = 30)
 * @method static mixed heapsnapshot()
 * @method static mixed browserTrace(?float $seconds = 30, ?array $categories = ['*'], ?string $session = null)
 * @method static mixed convertVoice(?string $url = null, ?string $data = null, ?string $session = null)
 * @method static mixed convertVideo(?string $url = null, ?string $data = null, ?string $session = null)
 * @method static array getLanguages()
 */
class Waha extends Facade
{
    protected static function getFacadeAccessor(): string
    {
        return 'waha';
    }
}
